apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ponarqube-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10000Mi
  storageClassName: ponarqube-storage
