apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:latest
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "1536Mi"
            cpu: "750m"
        ports:
          - containerPort: 9000
