apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5000Mi
  storageClassName: sonarqube-data-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-conf-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5000Mi
  storageClassName: sonarqube-conf-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-logs-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5000Mi
  storageClassName: sonarqube-logs-storage
