global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'Web-VMs'
    static_configs:
      - targets: ['web-1.bgapp.test:9100']
      - targets: ['web-2.bgapp.test:9100']
      - targets: ['web-3.bgapp.test:9100']
      
  - job_name: 'DB-VM'
    static_configs:
      - targets: ['db.bgapp.test:9100']
      
  # - job_name: 'JH-VM'
  #   static_configs:
  #     - targets: ['bgapp-jh-vm.bgapp.test:9100']
