---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pv
  namespace: monitoring
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: "azure-disk-storage"
  azureDisk:
    cachingMode: None # Can be None, ReadOnly, or ReadWrite
    diskName: monitoring-disk
    diskURI: /subscriptions/{sub-id}/resourcegroups/{group-name}/providers/microsoft.compute/disks/{disk-id}
    kind: Managed
    fsType: ext4
