apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgapp-web-deployment
  namespace: bgapp
  labels:
    app: bgapp-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bgapp
  template:
    metadata:
      labels:
        app: bgapp-web
    spec:
      containers:
      - name: bgapp-web
        image: stoimenovrado/bgapp-web
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
          - containerPort: 80
        env:
          - name: DB_HOST
            value: db
          - name: DB_PORT
            value: "3306"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
